"""add_exercises_and_references

Revision ID: d3d21c08247a
Revises: 88eaf54337ff
Create Date: 2026-03-22 15:47:00.935236+00:00

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = 'd3d21c08247a'
down_revision = '88eaf54337ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name=op.f('uq_equipment_name'))
    )
    op.create_table('exercise_tags',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_tags')),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name=op.f('uq_exercise_tags_name'))
    )
    op.create_table('muscle_groups',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_muscle_groups')),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name=op.f('uq_muscle_groups_name'))
    )
    op.execute("CREATE TYPE force_enum AS ENUM ('pull', 'push', 'static')")
    op.execute("CREATE TYPE difficulty_level_enum AS ENUM ('beginner', 'intermediate', 'expert')")
    op.execute("CREATE TYPE mechanic_enum AS ENUM ('compound', 'isolation')")
    op.execute("CREATE TYPE category_enum AS ENUM ('strength', 'stretching', 'plyometrics', 'strongman', 'powerlifting', 'cardio', 'olympic weightlifting')")
    op.create_table('exercises',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('force', postgresql.ENUM(name='force_enum', create_type=False), nullable=True),
    sa.Column('difficulty_level', postgresql.ENUM(name='difficulty_level_enum', create_type=False), nullable=False),
    sa.Column('mechanic', postgresql.ENUM(name='mechanic_enum', create_type=False), nullable=True),
    sa.Column('category', postgresql.ENUM(name='category_enum', create_type=False), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('image_path_start', sa.String(length=512), nullable=True),
    sa.Column('image_path_end', sa.String(length=512), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], name=op.f('fk_exercises_created_by_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index('uq_exercise_created_by_user', ['created_by', 'name'], unique=True, postgresql_where=sa.text('created_by IS NOT NULL'))
        batch_op.create_index('uq_sys_exercise_name', ['name'], unique=True, postgresql_where=sa.text('is_system_default IS true'))
        batch_op.create_index('uq_sys_exercise_slug', ['slug'], unique=True, postgresql_where=sa.text('is_system_default IS true'))

    op.create_table('exercise_equipment',
    sa.Column('exercise_id', sa.GUID(length=16), nullable=False),
    sa.Column('equipment_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_exercise_equipment_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_equipment_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'equipment_id', name=op.f('pk_exercise_equipment'))
    )
    with op.batch_alter_table('exercise_equipment', schema=None) as batch_op:
        batch_op.create_index('idx_ex_equipment_id', ['equipment_id'], unique=False)

    op.create_table('exercise_primary_muscles',
    sa.Column('exercise_id', sa.GUID(length=16), nullable=False),
    sa.Column('muscle_group_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_primary_muscles_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], name=op.f('fk_exercise_primary_muscles_muscle_group_id_muscle_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_group_id', name=op.f('pk_exercise_primary_muscles'))
    )
    with op.batch_alter_table('exercise_primary_muscles', schema=None) as batch_op:
        batch_op.create_index('idx_ex_primary_muscle_id', ['muscle_group_id'], unique=False)

    op.create_table('exercise_secondary_muscles',
    sa.Column('exercise_id', sa.GUID(length=16), nullable=False),
    sa.Column('muscle_group_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_secondary_muscles_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], name=op.f('fk_exercise_secondary_muscles_muscle_group_id_muscle_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_group_id', name=op.f('pk_exercise_secondary_muscles'))
    )
    with op.batch_alter_table('exercise_secondary_muscles', schema=None) as batch_op:
        batch_op.create_index('idx_ex_secondary_muscle_id', ['muscle_group_id'], unique=False)

    op.create_table('exercise_tag_map',
    sa.Column('exercise_id', sa.GUID(length=16), nullable=False),
    sa.Column('tag_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_tag_map_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['exercise_tags.id'], name=op.f('fk_exercise_tag_map_tag_id_exercise_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'tag_id', name=op.f('pk_exercise_tag_map'))
    )
    with op.batch_alter_table('exercise_tag_map', schema=None) as batch_op:
        batch_op.create_index('idx_ex_tag_map_tag_id', ['tag_id'], unique=False)

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Users accounts for application access',
        existing_comment=None
    )

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Users accounts for application access'
    )

    with op.batch_alter_table('exercise_tag_map', schema=None) as batch_op:
        batch_op.drop_index('idx_ex_tag_map_tag_id')

    op.drop_table('exercise_tag_map')
    with op.batch_alter_table('exercise_secondary_muscles', schema=None) as batch_op:
        batch_op.drop_index('idx_ex_secondary_muscle_id')

    op.drop_table('exercise_secondary_muscles')
    with op.batch_alter_table('exercise_primary_muscles', schema=None) as batch_op:
        batch_op.drop_index('idx_ex_primary_muscle_id')

    op.drop_table('exercise_primary_muscles')
    with op.batch_alter_table('exercise_equipment', schema=None) as batch_op:
        batch_op.drop_index('idx_ex_equipment_id')

    op.drop_table('exercise_equipment')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index('uq_sys_exercise_slug', postgresql_where=sa.text('is_system_default IS true'))
        batch_op.drop_index('uq_sys_exercise_name', postgresql_where=sa.text('is_system_default IS true'))
        batch_op.drop_index('uq_exercise_created_by_user', postgresql_where=sa.text('created_by IS NOT NULL'))

    op.drop_table('exercises')
    op.execute("DROP TYPE force_enum")
    op.execute("DROP TYPE difficulty_level_enum")
    op.execute("DROP TYPE mechanic_enum")
    op.execute("DROP TYPE category_enum")
    op.drop_table('muscle_groups')
    op.drop_table('exercise_tags')
    op.drop_table('equipment')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
