# ruff: noqa: S105
USER_LIST = "/users"
USER_DETAIL = "/users/{user_id}"
USER_CREATE = "/users"
USER_UPDATE = "/users/{user_id}"
USER_DELETE = "/users/{user_id}"
ACCOUNT_REGISTER = "/access/signup"
ACCOUNT_LOGIN = "/access/signin"
ACCOUNT_LOGOUT = "/access/logout"
ACCOUNT_REFRESH_TOKEN = "/access/refresh-jwt"
ACCOUNT_PWD_UPDATE = "/access/password-update"
ACCOUNT_PROFILE = "/access/me"
ACCOUNT_ASSIGN_ROLE = "/roles/{email}/assign"
ACCOUNT_REVOKE_ROLE = "/roles/{email}/revoke"
