name: Docs Build

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'docs/**'
      - 'src/**'
      - 'pyproject.toml'
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  UV_LOCKED: "1"
  PYTHON_VERSION: "3.12"

jobs:
  docs:
    name: Build and Deploy Docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install uv & Python
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --no-default-groups --group docs

      - name: Generate Changelog
        if: github.event_name != 'pull_request'
        uses: orhun/git-cliff-action@v4.7.1
        with:
          config: pyproject.toml
          args: --verbose --all-tags --output docs/changelog.rst

      - name: Commit updated changelog
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs: update changelog [skip ci]"
          file_pattern: docs/changelog.rst

      - name: Build Docs
        run: |
          uv run make docs
          touch docs/_build/html/.nojekyll

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          folder: docs/_build/html
          branch: gh-pages
          clean: true